### ISSUE TITLE
ModuleNotFoundError: No module named 'creativeai.image'

### ISSUE THREAD

**Issue by rainerkohlberger** [photogeniq/neural-texturize#6]
Hi,
unfortunately this errors gets thrown, although the creativeai pip package seems to be installed ('Requirement already satisfied'). What could be wrong? Thanks

```
Traceback (most recent call last):
  File "/home/rainer/miniconda3/envs/myenv/bin/texturize", line 11, in <module>
    load_entry_point('texturize', 'console_scripts', 'texturize')()
  File "/home/rainer/miniconda3/envs/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rainer/miniconda3/envs/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/rainer/miniconda3/envs/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/rainer/miniconda3/envs/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rainer/dev/texturize/src/texturize/__main__.py", line 56, in <module>
    from creativeai.image.encoders import models
ModuleNotFoundError: No module named 'creativeai.image'
```

**Comment by alexjc** [comment]
I'm just working on this, I found some issues with Python 3.8.  Maybe there's an `__init__.py` missing the in creativeai.image folder.

Let me look into it!

**Comment by alexjc** [comment]
I pushed `creativeai 0.1.1` which should fix this issue... Now adding more tests via GitHub actions to catch this!
